#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

if [ -f `which powerline-daemon` ]; then
  powerline-daemon -q
  . /usr/share/powerline/zsh/powerline.zsh
fi

# Setting up sqlite3 history for ZSH.

source "${HOME}/.zsh-histdb/sqlite-history.zsh"

autoload -Uz add-zsh-hook
add-zsh-hook precmd  histdb-update-outcome

# Environment Variables.

export EDITOR="/home/afronski/.user-scripts/e"
export GIT_EDITOR=$EDITOR
export VISUAL=$EDITOR

export AWS_DEFAULT_PROFILE="work"

export NODEJS_CHECK_SIGNATURES="no"
export GOPATH="/home/afronski/Repositories/golang"

alias grep="/usr/bin/grep $GREP_OPTIONS"
unset GREP_OPTIONS

source "/home/afronski/.zprivate"

# Aliases.

alias ls="ls --color=auto"
alias ll="ls -Llah"

alias grep="grep --color=auto"

alias vagrant="/usr/bin/vagrant"
alias bvagrant="bundle exec vagrant"

alias ghci="ghci-color"
alias vim="e"

alias pbcopy='xclip -i'
alias pbpaste='xclip -o'

. ${HOME}/.asdf/asdf.sh
. ${HOME}/.asdf/completions/asdf.bash

NODEJS="`asdf current nodejs | awk '{print $1}'`"

export PATH="${PATH}:/home/afronski/.user-scripts:/home/afronski/.private:/home/afronski/.local/bin:/home/afronski/.asdf/installs/nodejs/${NODEJS}/bin:/home/afronski/.asdf/installs/nodejs/${NODEJS}/.npm/bin"

[[ -f /home/afronski/.asdf/installs/nodejs/${NODEJS}/.npm/lib/node_modules/serverless/node_modules/tabtab/.completions/serverless.zsh ]] && . /home/afronski/.asdf/installs/nodejs/${NODEJS}/.npm/lib/node_modules/serverless/node_modules/tabtab/.completions/serverless.zsh
[[ -f /home/afronski/.asdf/installs/nodejs/${NODEJS}/.npm/lib/node_modules/serverless/node_modules/tabtab/.completions/sls.zsh ]] && . /home/afronski/.asdf/installs/nodejs/${NODEJS}/.npm/lib/node_modules/serverless/node_modules/tabtab/.completions/sls.zsh
