#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

if [ -f `which powerline-daemon` ]; then
  powerline-daemon -q
  . /usr/share/powerline/zsh/powerline.zsh
fi

# Setting up sqlite3 history for ZSH.

source "${HOME}/.zsh-histdb/sqlite-history.zsh"
source "${HOME}/.zsh-histdb/history-timer.zsh"

autoload -Uz add-zsh-hook
add-zsh-hook preexec _start_timer
add-zsh-hook precmd  _stop_timer

# Environment Variables.

export PATH="${PATH}:/home/afronski/.user-scripts:/home/afronski/.private:/home/afronski/.local/bin"

export EDITOR="/home/afronski/.user-scripts/e"
export GIT_EDITOR=$EDITOR
export VISUAL=$EDITOR

export AWS_DEFAULT_PROFILE="work"

alias grep="/usr/bin/grep $GREP_OPTIONS"
unset GREP_OPTIONS

source "/home/afronski/.zprivate"

# Aliases.

alias ls="ls --color=auto"
alias ll="ls -Llah"

alias grep="grep --color=auto"

alias vagrant="/usr/bin/vagrant"
alias bvagrant="bundle exec vagrant"

alias ghci="ghci-color"
alias vim="e"

. ${HOME}/.asdf/asdf.sh
. ${HOME}/.asdf/completions/asdf.bash
