#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block, everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

if [ -f `which powerline-daemon` ]; then
  powerline-daemon -q
fi

function pretty_csv {
  column -t -s, -n "$@" | less -F -S -X -K
}

# Setting up sqlite3 history for ZSH.

source "${HOME}/.zsh-histdb/sqlite-history.zsh"

autoload -Uz add-zsh-hook
add-zsh-hook precmd  histdb-update-outcome

# Environment Variables.

export EDITOR="/home/afronski/.user-scripts/e"
export GIT_EDITOR=$EDITOR
export VISUAL=$EDITOR

export NODEJS_CHECK_SIGNATURES="no"
export GOPATH="/home/afronski/work/golang"

alias grep="/usr/bin/grep $GREP_OPTIONS"
unset GREP_OPTIONS

source "/home/afronski/.zprivate"

# Aliases.

alias ls="ls --color=auto"
alias ll="ls -Llah"

alias grep="grep --color=auto"

alias vagrant="/usr/bin/vagrant"
alias bvagrant="bundle exec vagrant"

alias ghci="ghci-color"
alias vim="e"

alias pbcopy='xclip -i'
alias pbpaste='xclip -o'

. ${HOME}/.asdf/asdf.sh

NODEJS="`asdf current nodejs | awk '{print $1}'`"

export PATH="${PATH}:/home/afronski/.user-scripts:/home/afronski/.private:/home/afronski/.local/bin:/home/afronski/.asdf/installs/nodejs/${NODEJS}/bin:/home/afronski/.asdf/installs/nodejs/${NODEJS}/.npm/bin:/home/afronski/.Nozbe/:/opt/chefdk/embedded/bin"

[[ -f /home/afronski/.asdf/installs/nodejs/6.10.3/.npm/lib/node_modules/serverless/node_modules/tabtab/.completions/serverless.zsh ]] && . /home/afronski/.asdf/installs/nodejs/6.10.3/.npm/lib/node_modules/serverless/node_modules/tabtab/.completions/serverless.zsh

[[ -f /home/afronski/.asdf/installs/nodejs/6.10.3/.npm/lib/node_modules/serverless/node_modules/tabtab/.completions/sls.zsh ]] && . /home/afronski/.asdf/installs/nodejs/6.10.3/.npm/lib/node_modules/serverless/node_modules/tabtab/.completions/sls.zsh

export PATH="$PATH:/opt/yarn-/bin"

export ERL_AFLAGS="-kernel shell_history enabled"

export _JAVA_AWT_WM_NONREPARENTING=1

setxkbmap -option "nbsp:none"

function npm-do { (PATH=$(npm bin):$PATH; eval $@;) }

source ~/.powerlevel10k/powerlevel10k.zsh-theme
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

export PATH="/home/afronski/.ebcli-virtual-env/executables:${PATH}"
export PATH="${PATH}:/opt/gradle/gradle-6.4.1/bin"

# tabtab source for serverless package
# uninstall by removing these lines or running `tabtab uninstall serverless`
[[ -f /home/afronski/work/repositories/bitbucket/pattern-match/from-zero-to-aws-serverless-hero-cdk/aws-text-reader/day-2/step-0-with-no-changes/backend/node_modules/tabtab/.completions/serverless.zsh ]] && . /home/afronski/work/repositories/bitbucket/pattern-match/from-zero-to-aws-serverless-hero-cdk/aws-text-reader/day-2/step-0-with-no-changes/backend/node_modules/tabtab/.completions/serverless.zsh
# tabtab source for sls package
# uninstall by removing these lines or running `tabtab uninstall sls`
[[ -f /home/afronski/work/repositories/bitbucket/pattern-match/from-zero-to-aws-serverless-hero-cdk/aws-text-reader/day-2/step-0-with-no-changes/backend/node_modules/tabtab/.completions/sls.zsh ]] && . /home/afronski/work/repositories/bitbucket/pattern-match/from-zero-to-aws-serverless-hero-cdk/aws-text-reader/day-2/step-0-with-no-changes/backend/node_modules/tabtab/.completions/sls.zsh
# tabtab source for slss package
# uninstall by removing these lines or running `tabtab uninstall slss`
[[ -f /home/afronski/work/repositories/bitbucket/pattern-match/from-zero-to-aws-serverless-hero-cdk/aws-text-reader/day-2/step-0-with-no-changes/backend/node_modules/tabtab/.completions/slss.zsh ]] && . /home/afronski/work/repositories/bitbucket/pattern-match/from-zero-to-aws-serverless-hero-cdk/aws-text-reader/day-2/step-0-with-no-changes/backend/node_modules/tabtab/.completions/slss.zsh
